name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - name: lowlighter/metrics 😁
        uses: lowlighter/metrics@latest
        with:
          user: thequackyduck
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          plugin_languages: yes
          plugin_languages_colors: "0:orange, javascript:#ff0000, ..."  
          plugin_languages_aliases: "JavaScript:JS, TypeScript:TS, ..." 
          plugin_languages_details: bytes-size, percentage              
          plugin_la nguages_threshold: 2%                             
          plugin_languages_limit: 20                               
          plugin_languages_indepth: no                                  
          plugin_languages_recent_load: 500                             
          plugin_languages_recent_days: 7  
          plugin_activity: yes
          plugin_activity_limit: 8                                 
          plugin_activity_days: 14                                      # haha                      e
          plugin_activity_filter: push, issue, pr, ref/create, ref/delete, release, review, comment, wiki, fork, public, member 
          commits_authoring: lowlighter@users.noreply.github.com     
